### ISSUE TITLE
Enhancement: option to disable syntastic when running :Acks

### ISSUE THREAD

**Issue by lencioni** [wincent/ferret#2]
I use Syntastic, but don't want it to run when doing multi-file find/replace via `:Acks` because it adds no value but it slows down the operation considerably. I have currently added the following mapping in a `.vim/after/plugin/ferret.vim` file:

``` vim
" Wrapper around ferret's `:Acks` to disable and re-enable syntastic for speed.
function! Acks(command)
  " Syntastic makes saving slow, and since we aren't looking at the files to see
  " the warnings, we want to disable it when running through the files.
  SyntasticToggleMode

  call ferret#private#acks(a:command)

  " Re-enable syntastic.
  SyntasticToggleMode
endfunction

command! -nargs=1 Acks call Acks(<q-args>)
```

But others might want this functionality and might benefit from having an option baked into ferret itself. I'm also a little uncomfortable calling into something labeled "private". However, this is simple enough that it probably doesn't add a whole lot of value to ferret, and I can see the argument for not wanting to support every other plugin. However, I believe that Syntastic is popular enough that it might be worth baking something like this in to an option.

Would you be open to a pull request that adds this feature?

**Comment by wincent** [comment]
> I'm also a little uncomfortable calling into something labeled "private". 

So I could have made stuff truly private by making the functions script-local, but I preferred to use autoloading instead in order to optimize start-up time. The "private" in the name is therefore really just advisory, as in "this is an implementation detail, so if you build on top of it, be aware that your shit may break in the future". So it's not truly private, but I consider it be an example of "strong opinions weakly held", because it basically says "I don't think you should use this, but I won't try to stop you either".

Anyway, about the idea, I think we can definitely do this, but I think it should be implemented as a `User` autocommand. Get Ferret to fire a `FerretWillAcks` autocommand before running, and then `FerretDidAcks` afterward. Perhaps not those names, but something like them. This approach can then be leverage to turn off Syntastic in your case, or do whatever else other people might care about. (For an example, see what I did over here: https://github.com/wincent/ultisnips/commit/73a05a2a3b220be02e78412ce4bd32f81044fbf3).

**Comment by lencioni** [comment]
>  I think it should be implemented as a User autocommand.

Ah yes, I remember the work you did on UltiSnips. I think this is a good compromise.
