### ISSUE TITLE
Don't bind to Leader by default

### ISSUE THREAD

**Issue by greduan** [wincent/ferret#26]
IMO this is only prone to problems, I personally have bound `a` and `s`, this plugin would overwrite those.

It provides `<Plug>` bindings, so it isn't necessary to bind it to anything by default, let the user figure that out.

**Comment by wincent** [comment]
Thanks for raising this @greduan, but I disagree. It won't overwrite your bindings because of the [maparg checks](https://github.com/wincent/ferret/blob/7a9f763db6bc10193eb23f57ae4793fa52a06e53/plugin/ferret.vim#L48). Furthermore, even if I were to remove them then I'd break the existing setups of people who may be relying on them being set up by default. So I think things should stay the way they are.

**Comment by greduan** [comment]
Oh OK, if it does the check then it's all right. I just don't like when stuff is bound automatically.

Always worth mentioning [xkcd's comic](https://xkcd.com/1172/) on the topic. :)
