### ISSUE TITLE
Search inside git repo?

### ISSUE THREAD

**Issue by demon386** [wincent/ferret#51]
Is it possible to fix the search range inside git repo, rather than <pwd>?

**Comment by wincent** [comment]
If I understand the question, you want to search with `git grep`? Ferret doesn't know how to do that, but I imagine it could be added fairly easily (Ferret already knows how to support `ack`, `ag`, `rg` etc) if you wanted to send a PR. I never felt the need to add it myself because `rg` in particular is already very fast, but I wouldn't be averse to including it if somebody wanted to do the work.

**Comment by kriansa** [comment]
Do you think #46 could solve that?

**Comment by demon386** [comment]
Yes. Thanks
