### ISSUE TITLE
FerretAckWord should pass -w option by default

### ISSUE THREAD

**Issue by dlee** [wincent/ferret#66]
FerretAckWord should pass -w option by default. Right now, it's ignoring word boundaries.

**Comment by wincent** [comment]
This is by design (ie. it is intended to behave more like `g*` (`:h gstar`) than `*` (`:h star`) in Vim).

But I can see why you might want this. Given that it would be a breaking change, I'd want it to be guarded behind an option, and that option would default in such a way as to preserve the existing behavior.

**Comment by wincent** [comment]
Ok, the new option is now on the "master" branch.
