### ISSUE TITLE
Add a function that prompts for a search query

### ISSUE THREAD

**Issue by cweagans** [wincent/ferret#72]
I have the following mappings for `fzf`:

```vim
	nnoremap <leader>f :Files<CR>
	nnoremap <leader>b :Buffers<CR>
```

I'd like to add another one for Ferret like so:

```vim
	nnoremap <leader>s :Ack<CR>
```

But `:Ack` alone isn't a valid thing since it requires an argument. It'd be cool if there was a different thing I could map to that would prompt me for a search term. Bonus points if it auto-updates the quickfix window as I type (like how `fzf` does).

**Comment by wincent** [comment]
Not really sure I get the difference between prompting for a search term and just typing it in the command line (eg. [this mapping](https://github.com/wincent/ferret/blob/6218891a01418377c67b12ad57046ec78958ced2/plugin/ferret.vim#L733), which is to `:Ack<space>`); ie. I hit my mapping (in my case, `<Leader>a`), then start typing my query and hit `<CR>`.

You could certainly set up something to update the listing on every key-press, but performance might be a bit of an issue. I'm doing something similar in my dotfiles where I set up [a `CmdlineChanged` autocmd](https://github.com/wincent/wincent/blob/127e2e54d863f33d2a2fe182bfce489a9814f0da/aspects/vim/files/.vim/pack/bundle/opt/corpus/plugin/corpus.vim#L8) that ends up doing [a `git grep`](https://github.com/wincent/wincent/blob/127e2e54d863f33d2a2fe182bfce489a9814f0da/aspects/vim/files/.vim/pack/bundle/opt/corpus/autoload/corpus.vim#L817-L829) to show a list of matching files [in a Neovim floating window](https://github.com/wincent/wincent/blob/127e2e54d863f33d2a2fe182bfce489a9814f0da/aspects/vim/files/.vim/pack/bundle/opt/corpus/autoload/corpus.vim#L719-L746). That works only because `git grep` is fast, so I'm not sure the approach would scale to general usage in the context of Ferret (if you work in a big repo, at least, I can't see it working). If you're curious to see what this looks like in practice, I demoed an early version of this in [a screencast](https://youtu.be/KRlNBcYw74I) about a month ago.

**Comment by cweagans** [comment]
That's a really good point. tbh, I didn't even think about that approach. That's what I get for using vscode for so long :D 

Thanks for the pointers! Super helpful.
