### ISSUE TITLE
Delete quickfix/loclist to empty will cause ferret#private#qf_delete error

### ISSUE THREAD

**Issue by crispgm** [wincent/ferret#83]
Reproduction steps:
1. Create a qflist or loclist manually or by any plugins.
    e.g., `call setqflist([{'text':'aaa','type':'w'}], 'a')` and then `copen 1`
2. Delete the item by `dd`
3. It will show an error:
    <img width="658" alt="image" src="https://user-images.githubusercontent.com/1425636/163710929-3c1d747d-a6f2-4190-a608-8866735830b8.png">

**Comment by wincent** [comment]
Thanks for the report @crispgm. I _think_ this is fixed by cdccc5f6fce7d679403f9b734df7ae4f1ec96167 — I say "think" because I added an `if` check to stop the `E42` error (caused by Ferret trying to jump to the "next" item in the listing, which won't exist after deleting the last item), but I didn't see the `E684` error, so not sure how to reproduce that one. I can imagine a line like this one triggering such an error:

https://github.com/wincent/ferret/blob/cdccc5f6fce7d679403f9b734df7ae4f1ec96167/autoload/ferret/private.vim#L23

And having typed out that sentence, I realize that you could cause it to throw an error by deleting (eg. `dd`) in an already-empty listing. I'll add one more commit now to stop that from happening.

**Comment by wincent** [comment]
Ok; [this](https://github.com/wincent/ferret/compare/73c3390900e67d2e690470622a1da76539453cf5..8421031d84c35c44c4dc5bfb0913e45b9fbd7df4) should do it.

**Comment by crispgm** [comment]
> Ok; [this](https://github.com/wincent/ferret/compare/73c3390900e67d2e690470622a1da76539453cf5..8421031d84c35c44c4dc5bfb0913e45b9fbd7df4) should do it.

@wincent yep, this works perfect. Thanks.
